<?xml version="1.0" encoding="utf-8"?><Database Name="db_Matrix" Class="MatrixLinQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\db_Matrix.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Matrix_Academy.Properties.Settings" SettingsPropertyName="db_MatrixConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.user_login" Member="user_logins">
    <Type Name="user_login">
      <Column Name="uId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="uPassword" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.teacher" Member="teachers">
    <Type Name="teacher">
      <Column Name="teacherId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="teacherName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="teacherEmail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="teacherContactNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="teacherBloodGroup" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="teacherReligion" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="teacherAddress" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="teacherDesignation" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="teacherJoinDate" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="teacherPayPerClass" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.section" Member="sections">
    <Type Name="section">
      <Column Name="sectionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sectionName" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="sID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sFatherName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sMotherName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sContactNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sGender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sAdress" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sDateOfBirth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sJoiningDate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sSchool" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sClass" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sSection" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sFees" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>