#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrix_Academy.Connection
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_Matrix")]
	public partial class MatrixLinQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertuser_login(user_login instance);
    partial void Updateuser_login(user_login instance);
    partial void Deleteuser_login(user_login instance);
    partial void Insertteacher(teacher instance);
    partial void Updateteacher(teacher instance);
    partial void Deleteteacher(teacher instance);
    partial void Insertsection(section instance);
    partial void Updatesection(section instance);
    partial void Deletesection(section instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    #endregion
		
		public MatrixLinQDataContext() : 
				base(global::Matrix_Academy.Properties.Settings.Default.db_MatrixConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MatrixLinQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MatrixLinQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MatrixLinQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MatrixLinQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<user_login> user_logins
		{
			get
			{
				return this.GetTable<user_login>();
			}
		}
		
		public System.Data.Linq.Table<teacher> teachers
		{
			get
			{
				return this.GetTable<teacher>();
			}
		}
		
		public System.Data.Linq.Table<section> sections
		{
			get
			{
				return this.GetTable<section>();
			}
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_login")]
	public partial class user_login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uId;
		
		private string _uName;
		
		private string _uPassword;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuIdChanging(int value);
    partial void OnuIdChanged();
    partial void OnuNameChanging(string value);
    partial void OnuNameChanged();
    partial void OnuPasswordChanging(string value);
    partial void OnuPasswordChanged();
    #endregion
		
		public user_login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uId
		{
			get
			{
				return this._uId;
			}
			set
			{
				if ((this._uId != value))
				{
					this.OnuIdChanging(value);
					this.SendPropertyChanging();
					this._uId = value;
					this.SendPropertyChanged("uId");
					this.OnuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string uName
		{
			get
			{
				return this._uName;
			}
			set
			{
				if ((this._uName != value))
				{
					this.OnuNameChanging(value);
					this.SendPropertyChanging();
					this._uName = value;
					this.SendPropertyChanged("uName");
					this.OnuNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uPassword", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string uPassword
		{
			get
			{
				return this._uPassword;
			}
			set
			{
				if ((this._uPassword != value))
				{
					this.OnuPasswordChanging(value);
					this.SendPropertyChanging();
					this._uPassword = value;
					this.SendPropertyChanged("uPassword");
					this.OnuPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.teacher")]
	public partial class teacher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _teacherId;
		
		private string _teacherName;
		
		private string _teacherEmail;
		
		private string _teacherContactNo;
		
		private string _teacherBloodGroup;
		
		private string _teacherReligion;
		
		private string _teacherAddress;
		
		private string _teacherDesignation;
		
		private string _teacherJoinDate;
		
		private int _teacherPayPerClass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnteacherIdChanging(int value);
    partial void OnteacherIdChanged();
    partial void OnteacherNameChanging(string value);
    partial void OnteacherNameChanged();
    partial void OnteacherEmailChanging(string value);
    partial void OnteacherEmailChanged();
    partial void OnteacherContactNoChanging(string value);
    partial void OnteacherContactNoChanged();
    partial void OnteacherBloodGroupChanging(string value);
    partial void OnteacherBloodGroupChanged();
    partial void OnteacherReligionChanging(string value);
    partial void OnteacherReligionChanged();
    partial void OnteacherAddressChanging(string value);
    partial void OnteacherAddressChanged();
    partial void OnteacherDesignationChanging(string value);
    partial void OnteacherDesignationChanged();
    partial void OnteacherJoinDateChanging(string value);
    partial void OnteacherJoinDateChanged();
    partial void OnteacherPayPerClassChanging(int value);
    partial void OnteacherPayPerClassChanged();
    #endregion
		
		public teacher()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacherId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int teacherId
		{
			get
			{
				return this._teacherId;
			}
			set
			{
				if ((this._teacherId != value))
				{
					this.OnteacherIdChanging(value);
					this.SendPropertyChanging();
					this._teacherId = value;
					this.SendPropertyChanged("teacherId");
					this.OnteacherIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacherName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string teacherName
		{
			get
			{
				return this._teacherName;
			}
			set
			{
				if ((this._teacherName != value))
				{
					this.OnteacherNameChanging(value);
					this.SendPropertyChanging();
					this._teacherName = value;
					this.SendPropertyChanged("teacherName");
					this.OnteacherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacherEmail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string teacherEmail
		{
			get
			{
				return this._teacherEmail;
			}
			set
			{
				if ((this._teacherEmail != value))
				{
					this.OnteacherEmailChanging(value);
					this.SendPropertyChanging();
					this._teacherEmail = value;
					this.SendPropertyChanged("teacherEmail");
					this.OnteacherEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacherContactNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string teacherContactNo
		{
			get
			{
				return this._teacherContactNo;
			}
			set
			{
				if ((this._teacherContactNo != value))
				{
					this.OnteacherContactNoChanging(value);
					this.SendPropertyChanging();
					this._teacherContactNo = value;
					this.SendPropertyChanged("teacherContactNo");
					this.OnteacherContactNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacherBloodGroup", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string teacherBloodGroup
		{
			get
			{
				return this._teacherBloodGroup;
			}
			set
			{
				if ((this._teacherBloodGroup != value))
				{
					this.OnteacherBloodGroupChanging(value);
					this.SendPropertyChanging();
					this._teacherBloodGroup = value;
					this.SendPropertyChanged("teacherBloodGroup");
					this.OnteacherBloodGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacherReligion", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string teacherReligion
		{
			get
			{
				return this._teacherReligion;
			}
			set
			{
				if ((this._teacherReligion != value))
				{
					this.OnteacherReligionChanging(value);
					this.SendPropertyChanging();
					this._teacherReligion = value;
					this.SendPropertyChanged("teacherReligion");
					this.OnteacherReligionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacherAddress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string teacherAddress
		{
			get
			{
				return this._teacherAddress;
			}
			set
			{
				if ((this._teacherAddress != value))
				{
					this.OnteacherAddressChanging(value);
					this.SendPropertyChanging();
					this._teacherAddress = value;
					this.SendPropertyChanged("teacherAddress");
					this.OnteacherAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacherDesignation", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string teacherDesignation
		{
			get
			{
				return this._teacherDesignation;
			}
			set
			{
				if ((this._teacherDesignation != value))
				{
					this.OnteacherDesignationChanging(value);
					this.SendPropertyChanging();
					this._teacherDesignation = value;
					this.SendPropertyChanged("teacherDesignation");
					this.OnteacherDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacherJoinDate", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string teacherJoinDate
		{
			get
			{
				return this._teacherJoinDate;
			}
			set
			{
				if ((this._teacherJoinDate != value))
				{
					this.OnteacherJoinDateChanging(value);
					this.SendPropertyChanging();
					this._teacherJoinDate = value;
					this.SendPropertyChanged("teacherJoinDate");
					this.OnteacherJoinDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacherPayPerClass", DbType="Int NOT NULL")]
		public int teacherPayPerClass
		{
			get
			{
				return this._teacherPayPerClass;
			}
			set
			{
				if ((this._teacherPayPerClass != value))
				{
					this.OnteacherPayPerClassChanging(value);
					this.SendPropertyChanging();
					this._teacherPayPerClass = value;
					this.SendPropertyChanged("teacherPayPerClass");
					this.OnteacherPayPerClassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.section")]
	public partial class section : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sectionId;
		
		private string _sectionName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsectionIdChanging(int value);
    partial void OnsectionIdChanged();
    partial void OnsectionNameChanging(string value);
    partial void OnsectionNameChanged();
    #endregion
		
		public section()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sectionId
		{
			get
			{
				return this._sectionId;
			}
			set
			{
				if ((this._sectionId != value))
				{
					this.OnsectionIdChanging(value);
					this.SendPropertyChanging();
					this._sectionId = value;
					this.SendPropertyChanged("sectionId");
					this.OnsectionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sectionName", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string sectionName
		{
			get
			{
				return this._sectionName;
			}
			set
			{
				if ((this._sectionName != value))
				{
					this.OnsectionNameChanging(value);
					this.SendPropertyChanging();
					this._sectionName = value;
					this.SendPropertyChanged("sectionName");
					this.OnsectionNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sID;
		
		private string _sName;
		
		private string _sFatherName;
		
		private string _sMotherName;
		
		private string _sContactNo;
		
		private string _sGender;
		
		private string _sAdress;
		
		private string _sDateOfBirth;
		
		private string _sJoiningDate;
		
		private string _sSchool;
		
		private string _sClass;
		
		private string _sSection;
		
		private int _sFees;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsIDChanging(int value);
    partial void OnsIDChanged();
    partial void OnsNameChanging(string value);
    partial void OnsNameChanged();
    partial void OnsFatherNameChanging(string value);
    partial void OnsFatherNameChanged();
    partial void OnsMotherNameChanging(string value);
    partial void OnsMotherNameChanged();
    partial void OnsContactNoChanging(string value);
    partial void OnsContactNoChanged();
    partial void OnsGenderChanging(string value);
    partial void OnsGenderChanged();
    partial void OnsAdressChanging(string value);
    partial void OnsAdressChanged();
    partial void OnsDateOfBirthChanging(string value);
    partial void OnsDateOfBirthChanged();
    partial void OnsJoiningDateChanging(string value);
    partial void OnsJoiningDateChanged();
    partial void OnsSchoolChanging(string value);
    partial void OnsSchoolChanged();
    partial void OnsClassChanging(string value);
    partial void OnsClassChanged();
    partial void OnsSectionChanging(string value);
    partial void OnsSectionChanged();
    partial void OnsFeesChanging(int value);
    partial void OnsFeesChanged();
    #endregion
		
		public Student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sID
		{
			get
			{
				return this._sID;
			}
			set
			{
				if ((this._sID != value))
				{
					this.OnsIDChanging(value);
					this.SendPropertyChanging();
					this._sID = value;
					this.SendPropertyChanged("sID");
					this.OnsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sName
		{
			get
			{
				return this._sName;
			}
			set
			{
				if ((this._sName != value))
				{
					this.OnsNameChanging(value);
					this.SendPropertyChanging();
					this._sName = value;
					this.SendPropertyChanged("sName");
					this.OnsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sFatherName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sFatherName
		{
			get
			{
				return this._sFatherName;
			}
			set
			{
				if ((this._sFatherName != value))
				{
					this.OnsFatherNameChanging(value);
					this.SendPropertyChanging();
					this._sFatherName = value;
					this.SendPropertyChanged("sFatherName");
					this.OnsFatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMotherName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sMotherName
		{
			get
			{
				return this._sMotherName;
			}
			set
			{
				if ((this._sMotherName != value))
				{
					this.OnsMotherNameChanging(value);
					this.SendPropertyChanging();
					this._sMotherName = value;
					this.SendPropertyChanged("sMotherName");
					this.OnsMotherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sContactNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sContactNo
		{
			get
			{
				return this._sContactNo;
			}
			set
			{
				if ((this._sContactNo != value))
				{
					this.OnsContactNoChanging(value);
					this.SendPropertyChanging();
					this._sContactNo = value;
					this.SendPropertyChanged("sContactNo");
					this.OnsContactNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sGender", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sGender
		{
			get
			{
				return this._sGender;
			}
			set
			{
				if ((this._sGender != value))
				{
					this.OnsGenderChanging(value);
					this.SendPropertyChanging();
					this._sGender = value;
					this.SendPropertyChanged("sGender");
					this.OnsGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAdress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sAdress
		{
			get
			{
				return this._sAdress;
			}
			set
			{
				if ((this._sAdress != value))
				{
					this.OnsAdressChanging(value);
					this.SendPropertyChanging();
					this._sAdress = value;
					this.SendPropertyChanged("sAdress");
					this.OnsAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDateOfBirth", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sDateOfBirth
		{
			get
			{
				return this._sDateOfBirth;
			}
			set
			{
				if ((this._sDateOfBirth != value))
				{
					this.OnsDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._sDateOfBirth = value;
					this.SendPropertyChanged("sDateOfBirth");
					this.OnsDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sJoiningDate", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sJoiningDate
		{
			get
			{
				return this._sJoiningDate;
			}
			set
			{
				if ((this._sJoiningDate != value))
				{
					this.OnsJoiningDateChanging(value);
					this.SendPropertyChanging();
					this._sJoiningDate = value;
					this.SendPropertyChanged("sJoiningDate");
					this.OnsJoiningDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sSchool", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sSchool
		{
			get
			{
				return this._sSchool;
			}
			set
			{
				if ((this._sSchool != value))
				{
					this.OnsSchoolChanging(value);
					this.SendPropertyChanging();
					this._sSchool = value;
					this.SendPropertyChanged("sSchool");
					this.OnsSchoolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sClass", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sClass
		{
			get
			{
				return this._sClass;
			}
			set
			{
				if ((this._sClass != value))
				{
					this.OnsClassChanging(value);
					this.SendPropertyChanging();
					this._sClass = value;
					this.SendPropertyChanged("sClass");
					this.OnsClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sSection", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sSection
		{
			get
			{
				return this._sSection;
			}
			set
			{
				if ((this._sSection != value))
				{
					this.OnsSectionChanging(value);
					this.SendPropertyChanging();
					this._sSection = value;
					this.SendPropertyChanged("sSection");
					this.OnsSectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sFees", DbType="Int NOT NULL")]
		public int sFees
		{
			get
			{
				return this._sFees;
			}
			set
			{
				if ((this._sFees != value))
				{
					this.OnsFeesChanging(value);
					this.SendPropertyChanging();
					this._sFees = value;
					this.SendPropertyChanged("sFees");
					this.OnsFeesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
